In [ ]:
#task 1

import math

def rotation_matrix_x(theta):

  cos_theta = math.cos(theta)
  sin_theta = math.sin(theta)
  return [[1, 0, 0],
          [0, cos_theta, -sin_theta],
          [0, sin_theta, cos_theta]]


def rotation_matrix_y(theta):

  cos_theta = math.cos(theta)
  sin_theta = math.sin(theta)
  return [[cos_theta, 0, sin_theta],
          [0, 1, 0],
          [-sin_theta, 0, cos_theta]]

def rotation_matrix_z(theta):

  cos_theta = math.cos(theta)
  sin_theta = math.sin(theta)
  return [[cos_theta, -sin_theta, 0],
          [sin_theta, cos_theta, 0],
          [0, 0, 1]]

# Example usage
theta_x = math.pi/4  # 45 degrees rotation around X-axis
rot_matrix_x = rotation_matrix_x(theta_x)
print("Rotation matrix around X-axis by 45 degrees:")
print(rot_matrix_x)

Rotation matrix around X-axis by 45 degrees:
[[1, 0, 0], [0, 0.7071067811865476, -0.7071067811865475], [0, 0.7071067811865475, 0.7071067811865476]]


In [ ]:
#task 2

import numpy as np

def combine_rotations(rot_mat1, rot_mat2):

  return np.matmul(rot_mat1, rot_mat2)  # Matrix multiplication using numpy


# Example usage (assuming you have rotation matrices from Lab 1)
combined_rot = combine_rotations(rot_matrix_x, rotation_matrix_y(math.pi/2))  # Rotate around X then Y by 90 degrees
print("Combined rotation matrix (X then Y 90 degrees):")
print(combined_rot)

Combined rotation matrix (X then Y 90 degrees):
[[ 6.12323400e-17  0.00000000e+00  1.00000000e+00]
 [ 7.07106781e-01  7.07106781e-01 -4.32978028e-17]
 [-7.07106781e-01  7.07106781e-01  4.32978028e-17]]
